version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  messagee.api:
    image: ${DOCKER_REGISTRY-}messageeapi
    build:
      context: .
      dockerfile: Messagee.API/Dockerfile
    depends_on:
      - rabbitmq
